version: '3.9'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: smartphone_store
      MYSQL_USER: alvlr
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql-db
    networks:
      - monitoring

  web-app:
    build: ./web-app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql-db
      MYSQL_DATABASE: smartphone_store
      MYSQL_USER: alvlr
      MYSQL_PASSWORD: test
    depends_on:
      - mysql-db
    container_name: web-app
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alertrules.yml:/etc/prometheus/alertrules.yml
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.yml:/etc/grafana/grafana.ini
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
    ports:
      - "9100:9100"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    container_name: alertmanager
    hostname: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    networks:
      - monitoring
      
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    volumes:
      - ./.my.cnf:/etc/mysql/.my.cnf
    ports:
      - "9104:9104"
    depends_on:
      - mysql-db
    networks:
      - monitoring
    command:
      - --config.my-cnf=/etc/mysql/.my.cnf
      - --no-collect.slave_status

networks:
  monitoring:
    driver: bridge
