global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web-app'
    static_configs:
      - targets: ['web-app:5000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['exporter:9100']


rule_files:
  - 'alertrules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
